---
title: "AE02 - Hello git"
author: "Johanna Alvarado"
date: "September 1, 2026"
format: html
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(datasauRus)

```

## Exercises

### Exercise 1

In the help file, it says there is 1846 rows and 3 columns. The variables listed are char, double, and another double. 

### Exercise 2

Let's look at what these datasets are with a frequency table of the `dataset` variable:

```{r count-dataset}
datasaurus_dozen %>%
  count(dataset) %>%
  print(13)
```

Now let's plot the data in the dino dataset:

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

And next calculate the correlation between `x` and `y` in this dataset:

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

```{r plot-star}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```
